INTLY-7629 - minor updates
integr8ly/user-documentation pull request #134
Opened 2020-05-07 16:38 UTC by pwright

2020-05-07 16:44 UTC, nebelsprachen reviewed
I'm probably doing something wrong ... but this isn't resolving for me

2020-05-07 16:48 UTC, briandooley requested changes

2020-05-07 16:48 UTC, briandooley commented on modules/ROOT/pages/_partials/gs-adding-custom-3scale-routes.adoc
> +. Set up your public base URL in APIcast as described in the link:{three-scale-docs}/html/administering_the_api_gateway/operating-apicast[3scale documentation].
Should this be single page html?
```suggestion
. Set up your public base URL in APIcast as described in the link:{three-scale-docs}/html-single/administering_the_api_gateway/operating-apicast[3scale documentation].
```

2020-05-07 16:48 UTC, briandooley commented on modules/ROOT/pages/_partials/gs-service-discovery-3scale.adoc
> +* link:https://access.redhat.com/documentation/en-us/red_hat_fuse/{fuse-version}/html/designing_apis/threescale-discover-service[Service Discovery] Fuse documentation.
```suggestion
* link:{fuse-docs}html/designing_apis/threescale-discover-service[Service Discovery] Fuse documentation.
```

2020-05-08 08:47 UTC, briandooley approved these changes

2020-05-08 10:08 UTC, merged