INTLY-1520 Add section for giving view access to shared fuse namespace
integr8ly/user-documentation pull request #15
Opened 2019-03-27 16:50 UTC by david-martin

See https://issues.jboss.org/browse/INTLY-1520.

2019-03-27 17:20 UTC, maleck13 approved these changes

2019-03-28 09:24 UTC, pwright requested changes

2019-03-28 09:24 UTC, pwright commented on docs/content/gs-adding-users-proc.adoc
> +== Allowing users to view integration pod logs & import Fuse Online services from OpenShift into 3Scale
@david-martin  would users know what 'integration pods' are?
how about 'Giving users  permissions to view integration logs and perform 3Scale service discovery'?

2019-03-28 09:24 UTC, pwright commented on docs/content/gs-adding-users-proc.adoc
> +If a user requires access to integration pod logs or wants to use the 'Import from OpenShift' service discovery feature in 3Scale to import Fuse Online services automatically, they will need the `vie
```suggestion
This procedure describes how to add the *view* role for a user if that user requires either of the following:

* link:https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.4/html-single/service_discovery/index[Service Discovery] in 3Scale, which an be used to add Fuse Online services automatically
* Access to Fuse Online integration logs
```

2019-03-28 09:24 UTC, pwright commented on docs/content/gs-adding-users-proc.adoc
> +While logged in as the customer-admin user with `oc`, run the following command, substituting the `userid` for whichever user you want to give view access to.
```suggestion
. Log into OpenShift using `oc` and the `customer-admin` credentials.
. Run the following command, where `<userid>` is the user you want to give the role to:
```

2019-03-28 10:03 UTC, merged