custom public 3scale base urls
integr8ly/user-documentation pull request #24
Opened 2019-04-17 14:12 UTC by pb82

User facing docs for setting up custom public base URLs in 3scale.

1.3 on OSD requires granting permissions to the customer-admin user first which is described in a SOP: https://github.com/integr8ly/help/pull/111

2019-04-17 15:29 UTC, david-martin requested changes
Verified.
It might be worth mentioning they can't delete routes that they've created.

This is a security thing to prevent the custom accidentally deleting an important route 

```
oc auth can-i create routes -n openshift-3scale --as="customer-admin"
yes

oc auth can-i delete routes -n openshift-3scale --as="customer-admin"
no - no RBAC policy matched

oc auth can-i update routes -n openshift-3scale --as="customer-admin"
yes
```

2019-04-17 15:45 UTC, pb82 commented
@david-martin added a note to clarify the deletion policy

2019-04-17 15:56 UTC, david-martin commented
@finp Would you mind taking a look at this

2019-04-17 16:11 UTC, pwright requested changes

2019-04-17 16:11 UTC, pwright commented on docs/content/gs-adding-custom-3scale-routes.adoc
> += Allow using public hosts for 3scale APIs in {PRODUCT}
```suggestion
= Creating custom urls for 3scale APIs
```

2019-04-17 16:11 UTC, pwright commented on docs/content/gs-adding-custom-3scale-routes.adoc
> +Customers might want to use public custom base URLs for their 3scale APIs. In order to allow that an OpenShift route has to be added to the 3scale namespace first.
```suggestion
If you use 3scale to manage your API, you might require that the API URL use a specific host and format. 
For example, you might want to expose an API as `https://mydomain.com/v1/getStuff`. 
To use a custom domain, you must create a route in the OpenShift 3scale project as described below
```

2019-04-17 16:11 UTC, pwright commented on docs/content/gs-adding-custom-3scale-routes.adoc
> +NOTE: The `customer-admin` user has the permissions required for the following steps.
```suggestion
.Prerequisites
* you must be logged in as the `customer-admin` user
* a custom domain registration
```

2019-04-17 16:11 UTC, pwright commented on docs/content/gs-adding-custom-3scale-routes.adoc
> +$ oc login -u customer-admin
@maleck13  I'm guessing we should avoid this in future, and go with something like:
Log in as a user with the `dedicated-admin` role.

2019-04-17 16:14 UTC, finp commented on docs/content/gs-adding-custom-3scale-routes.adoc
> +Create a file named `custom-route.yaml` with the following contents:
```suggestion
Create a file named `custom-route.yaml` using the appropriate values for `<route name>` and `<route host>`:
```

2019-04-17 16:14 UTC, finp commented on docs/content/gs-adding-custom-3scale-routes.adoc
> +Fill in `<route name>` and `<route host>` in line 4 and 7 then create the route:
remove if accepting edit above

2019-04-17 16:14 UTC, finp commented on docs/content/gs-adding-custom-3scale-routes.adoc
> +Fill in `<route name>` and `<route host>` in line 4 and 7 then create the route:
```suggestion
Create the route:
```

2019-04-17 16:16 UTC, finp commented on docs/content/gs-adding-custom-3scale-routes.adoc
> +NOTE: once a route has been created it can't be deleted by `customer-admin`. This is to prevent accidental deletion of the auto generated routes.
```suggestion
NOTE: You cannot delete any routes created using this method.```
1. I wonder if this needs to be at top of process
2. I don't think reason is appropriate here, but would make a good known issue in release notes

2019-04-17 16:17 UTC, finp commented on docs/content/gs-adding-custom-3scale-routes.adoc
> +== Configuring the public base URL in 3scale
```suggestion
.Additional Information
```

2019-04-17 16:17 UTC, finp commented on docs/content/gs-adding-custom-3scale-routes.adoc
> +Once the route is created in OpenShift it has to be configured in your APIcast instance.
move up to be at end of procedure

2019-04-17 16:18 UTC, finp commented on docs/content/gs-adding-custom-3scale-routes.adoc
> +Please refer to the relevant link:https://access.redhat.com/documentation/en-us/red_hat_3scale/2.3/html/deployment_options/apicast-overview#configure_your_service[3scale documentation] to set up your
```suggestion
See the link:https://access.redhat.com/documentation/en-us/red_hat_3scale/2.3/html/deployment_options/apicast-overview#configure_your_service[3scale documentation] for a description of how to set up your public base URL in APIcast.
```

2019-04-17 16:23 UTC, finp commented on docs/content/gs-adding-custom-3scale-routes.adoc
> +To learn more about public base URLs in 3scale have a look at link:https://access.redhat.com/documentation/en-us/red_hat_3scale/2.3/html/deployment_options/apicast-overview#public_base_url[this secti
```suggestion
See the https://access.redhat.com/documentation/en-us/red_hat_3scale_api_management/2.4/html-single/deployment_options/index#public_base_url[Public Base URL] documentation for an introduction to custom URLs.
```

2019-04-17 16:25 UTC, finp commented on docs/content/gs-adding-custom-3scale-routes.adoc
> +== Creating the OpenShift route
```suggestion
.Procedure
```

2019-04-17 16:27 UTC, pwright requested changes
@pb82 @david-martin maybe the easiest thing would be to either accept/reject my suggestions, then push to upstream and we take it from there?
(there still need to be some restructuring here, I think the last 'step' should be to 'goto 3scale docs'

2019-04-18 07:06 UTC, pb82 commented
@finp I'll address your comments and then we can either merge this or discuss further restructuring. I'm already referring to the 3scale docs in the last step, is there anything more that should be linked?

2019-04-18 13:59 UTC, finp commented on docs/content/gs-adding-custom-3scale-routes.adoc
> +$ oc login -u customer-admin
addressed in jira

2019-04-18 14:18 UTC, finp commented
going to handle follow on comments in a separate PR

2019-04-18 14:18 UTC, merged